import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Calculator from "./calculator/index";

export default function Home() {
  const [state, setState] = useState([]);
  const [inputVal, setInputState] = useState("");
  const [inputKey, setInputKeyState] = useState("");
  useEffect(() => {
    const getData = async () => {
      const res = await fetch(`/api/saveData/query`);
      const data = await res.json();
      console.log("异步请求", data);
      setState(data);
    };

    getData();
  }, []);

  const addDict = async () => {
    try {
      const res = await fetch(`/api/saveData/add`, {
        method: "POST",
        body: JSON.stringify({ key: inputKey, value: inputVal }),
      });
      const data = await res.json();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">SHUXINLIU </a>
        </h1>

        {/* <label>输入key</label>
        <input
          onChange={(e) => {
            setInputKeyState(e.target.value);
          }}
        />
        <label>输入value</label>
        <input
          onChange={(e) => {
            setInputState(e.target.value);
          }}
        />
        <button
          onClick={() => {
            state.push({ key: inputKey, value: inputVal });

            setState([...state]);
            addDict();
          }}
        >
          添加
        </button>
        <div>
          {state.map((item) => {
            return (
              <div key={item.key}>
                <code>
                  Key:{item.key} Value:{item.value}
                </code>
              </div>
            );
          })}
        </div> */}
      </main>
      <Calculator />
      <footer className={styles.footer}></footer>
    </div>
  );
}
