import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [state, setState] = useState([]);
  const [inputVal, setInputState] = useState('');
  const [inputKey, setInputKeyState] = useState('');
  useEffect(async () => {
    const res = await fetch(`/api/saveData/query`);
    const data = await res.json();
    console.log('异步请求', data);
    setState(data);
  }, []);

  const addDict = async () => {
    try {
      const res = await fetch(`/api/saveData/add`, {
        method: 'POST',
        body: JSON.stringify({ key: inputKey, value: inputVal }),
      });
      const data = await res.json();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">SHUXIN </a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
        <label>输入key</label>
        <input
          onChange={(e) => {
            setInputKeyState(e.target.value);
          }}
        />
        <label>输入value</label>
        <input
          onChange={(e) => {
            setInputState(e.target.value);
          }}
        />
        <button
          onClick={() => {
            state.push({ key: inputKey, value: inputVal });

            setState([...state]);
            addDict();
          }}
        >
          添加
        </button>
        <div>
          {state.map((item) => {
            return (
              <div key={item.key}>
                <code>
                  Key:{item.key} Value:{item.value}
                </code>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
